### ISSUE TITLE
Supported Hardware

### ISSUE THREAD

**Issue by fluidblue** [pupil-labs/pupil-mobile-app#6] opened 2017-05-23 09:32 UTC
Hi,

I am trying to use a Pupil headset with the Pupil Mobile app. I connected the headset to a OnePlus 2 USB-C phone, but the app didn't show the cameras.

According to the [Pupil UbiComp Paper](https://docs.pupil-labs.com/#ubicomp-2014-paper) Pupil used USB 2.0 in 2014. Which USB version is used now?
Are any other capabilities of USB used (e.g. USB Power Delivery)?

Regards,
Max

**Comment by mkassner** [comment] 2017-05-23 09:34
Hi Max,

if you have a recent headset it should have a usb c clip and using a usbc-to-c cable it should work!

**Comment by fluidblue** [comment] 2017-05-23 09:37
It is a headset with a usb-c clip and I used a usb-c to usb-c cable, but it didn't work..

**Comment by papr** [comment] 2017-05-23 09:38
Dear @fluidblue 

We use USB 2.0 cameras that are connected to a USB 3.0 hub. This is the usb-c clip mentioned above.

I use a OnePlus 3 and the cameras are all shown but I am only able to run more than two cameras at a time. It looks like the phone/kernel does not supply enough power to run 3 cameras.

If you want to run a binocular setup (3 cameras) we can recommend the Nexus 6P.

**Comment by fluidblue** [comment] 2017-05-30 10:30
Hello,

thanks for the answers.

Do all revision of the headset have a USB 3.0 hub?
In macOS 10.12.5, the System Information app shows a USB 2.0 hub for my headset, although it is connected to a USB 3.0 bus:
[sysinfo.txt](https://github.com/pupil-labs/pupil-mobile-app/files/1037975/sysinfo.txt)

Up to how much power does the headset consume?
Would it be possible to use a powered USB3.0 hub between phone and headset to overcome the power problem?

**Comment by maciejpl** [comment] 2017-06-09 13:05
Hello,

Could you provide me with information on what is the most important specification apart from the support for USB Type-C. For example the following smartphone (HTC 10), although untested by your company, technically should work?

http://www.htc.com/uk/smartphones/htc-10/ 

Its specifications looks very similar to that of Nexus 6P.

The problem is that my University can't buy refurbished device (Nexus 6P), so I'm looking for working alternative. Pupil Headset will be mono ocular.

I'll be grateful for any advice

**Comment by mkassner** [comment] 2017-06-12 12:42
Hi,

they this phone "should" work. But there is no way of knowing before having tried it.

**Comment by majoge** [comment] 2017-08-04 08:48
Tried a Huawei Nova with USB-C. Did not work. Please clarify, which features of USB are used.

**Comment by mkassner** [comment] 2017-08-04 15:10
@majoge  we found that often is not only the phone but android being a bit iffy with permissions. Sometimes it starts working with a reboot and a few plug-unplugs. 

We are still investigating. I have made very good experience with Nexus 5x and 6p.

**Comment by willpatera** [comment] 2018-01-24 03:49
I am closing this issue. We should document supported devices in the README instead of an issue.

**Closed by willpatera** 2018-01-24 03:49 UTC
