### ISSUE TITLE
Not working in Android 9

### ISSUE THREAD

**Issue by ewaldstrasser** [pupil-labs/pupil-mobile-app#32] opened 2018-12-22 15:51 UTC
I got the message that under Android 9 might not work anderen they so not work.
When ist this fixed?

**Comment by papr** [comment] 2019-01-21 14:48
Android 9 introduced system changes that make it impossible to detect/access the Pupil cameras. We are still investigating the issue but it looks like this is something that cannot be fixed on app-level. Therefore the warning.

**Comment by portas525** [comment] 2019-01-21 15:09
the two eyecams cams can be detected. the main problem (as I see) is the field cam. Also the streaming of the two eyecams over networks works fine. So "only" the fieldcam is missing. 
Best
portas525

**Comment by mkassner** [comment] 2019-01-22 15:17
The issue is that a number of uvc devices are for some reason no longer detected in Android 9. We are working on a fix for now he highly recommend NOT UPGRADING to android 9!

**Comment by mkassner** [comment] 2019-01-22 15:18
IF we can fix this it will require either a fix in Android or a firmware upgrade of the world camera.

**Comment by charlottevera** [comment] 2019-03-11 16:00
Is there any update on this issue? My OP6 with Android 9 doesn't recognize the eyetracker at all...but that might just be my inexperience with the software.

**Comment by mkassner** [comment] 2019-03-12 15:58
@charlottevera  unfortunately not. This Anroid9 bug cannot be worked around. You need to revert to android8.

**Comment by PapaFuchs** [comment] 2019-04-30 07:14
Note: **Possible solution** below.

As we really need your app to run on Android 9, I did some research for you, guys:

Afaik, the common way to use UVC devices in Android is the [UVCCamera](https://github.com/saki4510t/UVCCamera) library, so I assume you are using it too, right?
Although the active development on this library seems to have stopped quite a while ago, they have an [interesting open issue](https://github.com/saki4510t/UVCCamera/issues/436) (well, in fact they have a looot of open issues ;-) ) describing problems in Android 9 that fits to your issue here.

It looks like Android is using a different [USB class](https://www.usb.org/defined-class-codes) for some cameras since Android 9. That leads to a the described problem of "not detecting" the world camera, because the UVCCamera library uses a [filter](https://github.com/saki4510t/UVCCamera/blob/master/libuvccamera/src/main/java/com/serenegiant/usb/DeviceFilter.java) based on this USB class. I used Android's UsbManager to find out about these classes of the Pupil devices:

< Android 9:
Eye Cameras: Device Class 239
World Camera: Device Class 239

Android 9:
Eye Cameras: still Device Class 239
World Camera: **Device Class 14** (what actually stands for Video Interface)

So I thought it me worth a try to tell UVCCamera to also check for class 14 and voilà, it was possible to detect the world camera and capture its video stream. And that brings me to the

**Possible solution**:
As I am pretty sure you are using the UVCCamera library, use another DeviceFilter to also look for class 14 devices and this should be fixed. To be more specific, you could use [DeviceFilter](https://github.com/saki4510t/UVCCamera/blob/master/libuvccamera/src/main/java/com/serenegiant/usb/DeviceFilter.java)'s method 
`getDeviceFilters(final Context context, final int deviceFilterXmlId)`
to parse a resource XML file like this
```
<usb>
    <usb-device class="239" subclass="2" />
    <usb-device class="14" subclass="2" />
</usb>
```
having two different device classes for filtering.
I really think this will solve the issue, so please test it and build a new version as soon as anyhow possible, we need it! ;-)

**Comment by mkassner** [comment] 2019-05-06 14:04
@PapaFuchs we are looking into this! Thanks for the pointer!

**Comment by cynicer** [comment] 2019-05-09 10:18
Thanks @PapaFuchs for pointing out the solution! I've been hoping for a long time that this bug finally gets fixed. As it turns out it is indeed NOT impossible to detect the Pupil cameras in Android 9, with the correct device filters set. I unpacked the APK, inserted the suggested snippet and repacked it. Works now! :-) I'm hoping for an official update soon.

![photo_2019-05-09 12 16 05](https://user-images.githubusercontent.com/5718282/57446211-7ce96280-7254-11e9-85f1-fcda22b615fb.jpeg)
![photo_2019-05-09 12 15 57](https://user-images.githubusercontent.com/5718282/57446213-7f4bbc80-7254-11e9-8a47-c10fa47f66b9.jpeg)
![photo_2019-05-09 12 16 01](https://user-images.githubusercontent.com/5718282/57446217-807ce980-7254-11e9-8ba6-803fc6f14a6b.jpeg)

**Comment by portas525** [comment] 2019-05-09 13:32
Hello Marcel,
That loojs great. Will you share your app with me?
Thanks
Klaus

Am 9. Mai 2019 12:18:35 schrieb Marcel Breitenfellner 
<notifications@github.com>:

**Comment by mkassner** [comment] 2019-05-09 13:43
The current beta release of pupil mobile support android 9. While this is still a workaround it does allow to use USB Cameras on android 9 with Pupil Mobile.

**Closed by mkassner** 2019-05-09 13:43 UTC

**Comment by eicm** [comment] 2019-05-24 22:09
@mkassner I'm using a Pixel 3, how can I get the beta APK as I can't download it from playstore and haven't found the the latest beta release anywhere on the web

**Comment by papr** [comment] 2019-05-24 22:15
@eicm Have you joined the beta program? https://accounts.google.com/signin/v2/identifier?passive=1209600&continue=https%3A%2F%2Fplay.google.com%2Fapps%2Ftesting%2Fcom.pupillabs.pupilmobile&followup=https%3A%2F%2Fplay.google.com%2Fapps%2Ftesting%2Fcom.pupillabs.pupilmobile&flowName=GlifWebSignIn&flowEntry=ServiceLogin Afterwards, you should be able to download the beta from the Play Store.

**Comment by eicm** [comment] 2019-05-30 10:51
@papr Yes I did join the program but the download option is disabled on Pixel 3 (as it is nor listed as a supported device by pupil-labs)

**Comment by eicm** [comment] 2019-05-30 12:08
@papr I'm reading the source code to understand the calibration and 3D gaze estimation better, is there any literature to read more abt the techniques?

**Comment by papr** [comment] 2019-05-30 12:27
- Pupil Mobile - @saki4510t can you verify that the app has been disabled for Pixel 3 phones? If yes, do you remember the technical reason for doing so?

- 3d gaze estimation - The pipeline is based on [this paper](https://www.researchgate.net/profile/Lech_Swirski/publication/264658852_A_fully-automatic_temporal_approach_to_single_camera_glint-free_3D_eye_model_fitting/links/53ea3dbf0cf28f342f418dfe/A-fully-automatic-temporal-approach-to-single-camera-glint-free-3D-eye-model-fitting.pdf).

**Comment by saki4510t** [comment] 2019-05-30 14:28
@papr 
Previously Pupil Mobile can not work on any Android 9 device, so some devices (that only run with Android 9 like Pixel3) are disabled on Google Play to prevent installing. After releasing version 1.2.1 on beta track(yesterday), they were enabled again and will be available soon.

**Comment by papr** [comment] 2019-05-30 14:29
@saki4510t thank you very much for the update.

**Comment by eicm** [comment] 2019-05-30 15:37
Thanks for the update, I can verify that all 3 cameras work properly.

**Comment by MLT-SEP** [comment] 2019-08-30 08:23
I cannot use Pupil Mobile and I have Android 9. Does The problem still remain ? 
If so, is it possible to explain how Can I solve that please easily ? Maybe, they found New solution.

**Comment by papr** [comment] 2019-08-30 08:32
Please update your Pupil Mobile application. Version 1.2.1 includes a work-around that solves the issues with Android 9.

In case that none of the cameras are recognized, you might need to enable the OTG setting of your phone.

**Comment by MLT-SEP** [comment] 2019-10-02 15:46
I used Version 1.2.1 and I connect OTG setting on my phone. It worked but today I have still the same problem : no detection of the eye-tracker on the phone. Eye-tracker is detected on computer.  Could you help me again please to find solution ?

**Comment by papr** [comment] 2019-10-02 15:48
Hi @MLT-SEP How are you connecting the eye tracker to your phone? Make sure to use a proper USB-C to USB-C cable. Also which phone do you use?

**Comment by MLT-SEP** [comment] 2019-10-02 15:52
Hi,
Yes I use a proper USB-C to USB-C cable. I did not change the cable between yesterday and today. I tried with another cable just in case it was the cable but it did not work more.

**Comment by papr** [comment] 2019-10-02 15:54
Ah, my apologies, I misunderstood. Please check all cable connections and ensure OTG is turned on. It sometimes turns off automatically. Regarding the cable connection: Sometimes one has to push a little harder to connect the cable correctly to the hub.

**Comment by MLT-SEP** [comment] 2019-10-02 16:07
Thank you for your answer. Unfortunately, I am checking cable connections and OTG but nothing happens. Have you another idea ?

**Comment by papr** [comment] 2019-10-02 16:16
Not right, especially if it is still functional when connecting it directly to Capture.

**Comment by MLT-SEP** [comment] 2019-10-02 16:18
Yes it is functional on Pupil Capture on my computer.
